### ISSUE TITLE
答题总是服务器异常

### ISSUE THREAD

**Issue by roinu176** [XYenon/new-api-chaoxing-helper#1]
我有100G高防御服务器，要不用我的吧 总502

**Comment by XYenon** [comment]
答题的接口我是从[别的脚本](https://greasyfork.org/zh-CN/scripts/401403-new-%E8%B6%85%E6%98%9F%E7%BD%91%E8%AF%BE%E5%8A%A9%E6%89%8B)那拿来的，我也没有题库

**Comment by roinu176** [comment]
> 的答题我接口的英文从[别的脚本](https://greasyfork.org/zh-CN/scripts/401403-new-%E8%B6%85%E6%98%9F%E7%BD%91%E8%AF%BE%E5%8A%A9%E6%89%8B)那拿来的，我也没有题库
好吧
